#
# Configuration for services that shall have an api client be generated for
#

url:
  use_prefix_and_suffix: true
  # If true will handle each entry in services as middle part of the url
  # Set to false if entries in services are already complete urls

  prefix: https://dev-oxs.simplic.io/
  suffix: -api/v1/swagger/v1/swagger.json

# List all services/urls here
services:
  - x: ai
  - x: article
  - x: auth
  - x: cdn
  - x: construction-site
  - x: contact
  - x: contract
  - x: devops
  - x: document
  - x: erp
  - x: geo
  - x: logistics
  - x: organization
  - x: sensor
  - x: storage-management
  - x: timeslot
  - x: telematic
  - x: vehicle
  - x: vehicle-temperature
  # - x: ./test/sdk-test-swagger.json
  #   is_url: true
# if you want to override the title that is used for the last segment of the project name specify it like this:
# - x: your-service
#   title: YourCustomTitle
#
# when using prefix and suffix pattern, you can also have specific entries be interpreted as whole url's by specifying it like this:
# - x: your-host.com/your-service/your-specification.json
#   is_url: true
# (supports paths as well)
