/*
 * Simplic.OxS.Logistics
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Simplic.OxS.SDK.Logistics.Model;
using Simplic.OxS.SDK.Logistics.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Simplic.OxS.SDK.Logistics.Test.Model
{
    /// <summary>
    ///  Class for testing WeightNoteModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WeightNoteModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WeightNoteModel
        //private WeightNoteModel instance;

        public WeightNoteModelTests()
        {
            // TODO uncomment below to create an instance of WeightNoteModel
            //instance = new WeightNoteModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WeightNoteModel
        /// </summary>
        [Fact]
        public void WeightNoteModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" WeightNoteModel
            //Assert.IsType<WeightNoteModel>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'IsDeleted'
        /// </summary>
        [Fact]
        public void IsDeletedTest()
        {
            // TODO unit test for the property 'IsDeleted'
        }

        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Fact]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }

        /// <summary>
        /// Test the property 'DocumentId'
        /// </summary>
        [Fact]
        public void DocumentIdTest()
        {
            // TODO unit test for the property 'DocumentId'
        }

        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'CreateDateTime'
        /// </summary>
        [Fact]
        public void CreateDateTimeTest()
        {
            // TODO unit test for the property 'CreateDateTime'
        }

        /// <summary>
        /// Test the property 'FirstWeight'
        /// </summary>
        [Fact]
        public void FirstWeightTest()
        {
            // TODO unit test for the property 'FirstWeight'
        }

        /// <summary>
        /// Test the property 'SecondWeight'
        /// </summary>
        [Fact]
        public void SecondWeightTest()
        {
            // TODO unit test for the property 'SecondWeight'
        }

        /// <summary>
        /// Test the property 'FirstDateTime'
        /// </summary>
        [Fact]
        public void FirstDateTimeTest()
        {
            // TODO unit test for the property 'FirstDateTime'
        }

        /// <summary>
        /// Test the property 'SecondDateTime'
        /// </summary>
        [Fact]
        public void SecondDateTimeTest()
        {
            // TODO unit test for the property 'SecondDateTime'
        }

        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Fact]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
    }
}
